#!/usr/bin/env bash

# make symlinks of my dotfiles and put them in $HOME
FILES="vimrc bashrc bash_profile tmux.conf zshrc gitconfig Xresources xinitrc"

for file in $FILES
do
	echo "Symlinking $file"
	rm ~/.$file
	ln -s ${PWD}/$file ~/.$file

done 

# Link nvim config manually 
echo "Symlinking init.vim"
rm ~/.config/nvim/init.vim
ln -s ${PWD}/init.vim ~/.config/nvim/init.vim


