#!/usr/bin/env bash

# make symlinks of my dotfiles and put them in $HOME
FILES="vimrc bashrc tmux.conf xinitrc"


for file in $FILES
do
	echo "Symlinking $file"
	rm ~/.$file
	ln -s ${PWD}/$file ~/.$file

done 

# Make an xprofile for when not using startx
cp ~/.xinitrc ~/.xprofile

